server:
  port: ${SERVER_PORT:8081}

jwt:
  secret: ${JWT_SECRET:supersecretkey123}

catalog:
  service:
    url: ${CATALOG_SERVICE_URL:http://localhost:8082}

order:
  service:
    url: ${ORDER_SERVICE_URL:http://localhost:8083}

aws:
  endpoint: ${AWS_ENDPOINT:http://localhost:4566}
  region: ${AWS_REGION:us-east-1}
  access-key: ${AWS_ACCESS_KEY_ID:test}
  secret-key: ${AWS_SECRET_ACCESS_KEY:test}
  lambda:
    function: order-recommendation
