server:
  port: ${SERVER_PORT:8082}

spring:
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB:novamart}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
