worker_processes 1;

events { worker_connections 1024; }

http {
  upstream gateway_upstream {
    server gateway:8081;
  }

  server {
    listen 80;

    location /api/ {
      proxy_pass http://gateway_upstream/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location /ws/ {
      proxy_pass http://notification-service:8084/ws/;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "Upgrade";
    }

    location /catalog/ {
      proxy_pass http://catalog-mfe:80/;
    }

    location /orders/ {
      proxy_pass http://orders-mfe:80/;
    }

    location / {
      proxy_pass http://shell:80/;
    }
  }
}
